name: for_suyeon
description: Birthday anniversary app.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  sqflite: ^2.0.2
  path: ^1.8.0
  image: ^3.1.3
  url_launcher: ^6.1.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.10+1
  cloud_firestore: ^3.5.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/pw/
    - assets/letter/
    - assets/sample_image/
  fonts:
    - family: BinggraeSamanco
      fonts:
        - asset: assets/fonts/BinggraeSamanco-Regular.ttf
        - asset: assets/fonts/BinggraeSamanco-Bold.ttf

